services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=photo'
      - 'POSTGRES_PASSWORD=ffdev'
      - 'POSTGRES_USER=ffdev'
    ports:
      - '5434:5432'
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
