spring:
  application:
    name: showmethephoto

    profiles:
      default: local

      jpa:
        open-in-view: false
        hibernate:
          ddl-auto: validate

    server:
      port: 8081
