spring:
  application:
    name: showmethephoto

  profiles:
    default: local

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

server:
  port: 8081

app:
  jwt:
    secret: ${JWT_SECRET}
    access-token-ttl-seconds: 3600